name: egliloo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  get: ^4.7.3
  get_storage: ^2.1.1
  hive: ^2.2.3
  http: ^1.3.0

  # Shared Preferences & Storage
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  uuid: ^4.4.0

  # Network
  dio: ^5.9.2
  connectivity_plus: ^7.2.0

  # Media Players
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  video_player: ^2.11.1
  chewie: ^1.14.1

  # Images & Cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # UI, Layout & Design
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  google_fonts: ^8.1.0
  lottie: ^3.4.0
  shimmer: ^3.0.0
  animations: ^2.2.0
  carousel_slider: ^5.1.2
  flutter_staggered_grid_view: ^0.7.0

  # Markdown
  flutter_markdown_plus: ^1.0.7
  markdown: ^7.2.2

  # Pagination
  infinite_scroll_pagination: ^5.1.1

  # Utilities
  intl: ^0.20.3
  share_plus: ^13.2.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.3
  image_picker: ^1.2.2
  package_info_plus: ^10.2.0
  comment_tree_full: ^0.1.0
  provider: ^6.1.5+1
  path: ^1.9.1
  open_filex: ^4.7.0
  flutter_carousel_widget: ^3.1.1
  upgrader: ^13.5.0
  universal_downloader: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0 # Mettez à jour ici
  mockito: ^5.7.0 # Mettez à jour ici

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
